import datetime as dt, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/'experiments/current-sports-event-research.json'
def main():
 p=json.loads(PATH.read_text()); rows=p.get('research_items',[]); by={str(x.get('event_slug')):x for x in rows}
 by['col-dec1-lie-2026-07-15']={
  'event_slug':'col-dec1-lie-2026-07-15','event_id':'659487','game_id':'90112943','title':'FK Dečić Tuzi vs. FK Liepāja','target_market_id':'2771218','target_side':'YES','direction':'HOME','rules_clear':True,
  'settlement_rules':'Exact 90-minute Dečić win plus stoppage time; not qualification, extra time or penalties.','research_status':'insufficient','research_probability':None,'confidence_low':None,'confidence_high':None,'calibrated_oos_samples':0,'maximum_acceptable_price':None,
  'method':'UEFA/beIN/Sky/Sports Mole public records confirm a Conference League qualifying return leg and Liepāja 1-0 first-leg lead. Recent-form and one-match statistical anchors are available, but confirmed XI, opponent-adjusted 5-10 match sample, weather, fresh CLOB and reconciled independent probability are incomplete.',
  'key_evidence':['UEFA lineup page identifies Dečić vs Liepāja and the qualifying context.','Sky/Sports Mole report the first leg Liepāja 1-0, with Dečić reduced to ten men after a 21st-minute red card; the second-leg aggregate incentive materially separates advance from 90-minute win.','The current Polymarket scan shows a Dečić market price around 38c, but market price is only a benchmark.'],
  'first_goal_profile':'Dečić must chase the aggregate deficit and may create early pressure, but Liepāja can defend and counter; first-goal and chance-quality rates are not independently quantified.','trailing_response':'A Liepāja goal or a low-event draw makes the 90-minute home-win path poor; Dečić advancing requires a different contract analysis.','lead_protection':'A Dečić lead may still require further attacking effort because of the aggregate deficit, while Liepāja can protect or counter; substitutions and fitness are unverified.',
  'failure_paths':['Liepāja scores first','0-0/1-1 low-event draw','Dečić repeats discipline problems','rotation/injury','90-minute win differs from qualification','spread/fees/slippage erase edge'],
  'conditional_trigger':'Do not enter. Recheck confirmed XI, official match state, weather and fresh executable CLOB; only reconsider if independent evidence converges and net edge clears 5c.','live_playbook':{'required':'Only if score, minute and quote are each <=120 seconds old; monitor field tilt, box entries, shot quality, set pieces and red-card risk.','invalidate':'Stale data, red card, key injury or failure to create repeatable box access.'},'exit_plan':{'paper':'No paper position. If later evidenced, cap at 0.10u and hard-exit catalyst exposure before 23:50 Beijing.'},
  'research_missing_fields':['confirmed_starting_XI','complete_last_5_to_10_both_teams','opponent_strength_adjustment','verified_xG_or_shot_quality_sequence','injuries_and_suspensions','weather_at_venue','independent_probability','fresh_CLOB_depth_and_slippage'],'next_review_at':'2026-07-16T12:00:00+08:00','strength_classification':'研究候选但证据不足，不能升级为入场授权',
  'sources':[{'kind':'official','title':'UEFA Dečić vs Liepāja lineups','url':'https://fr.uefa.com/uefaconferenceleague/match/2048694--decic-vs-liepaja/lineups/'},{'kind':'independent','title':'Sky Sports first-leg data','url':'https://sport.sky.de/fussball/liepaja-vs-decic/daten/558206'},{'kind':'independent','title':'Sports Mole first-leg match guide','url':'https://www.sportsmole.co.uk/football/europa-conference-league/fk-liepaja-vs-decic_game_249814.html'}]}
 p.update({'schema_version':'polymarket-sports-event-research-v1','research_run_id':'pm-sports-research-'+dt.datetime.now(dt.timezone.utc).strftime('%Y%m%dT%H%M%SZ'),'created_at':dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace('+00:00','Z'),'report_date_beijing':'2026-07-16','research_items':list(by.values()),'paper_only':True,'live_orders_enabled':False,'private_api_used':False,'real_money_execution_authorized':False})
 PATH.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n'); print('updated uecl-dec-lie-2026-07-15')
if __name__=='__main__': main()
