#!/usr/bin/env python3
"""Upsert this hourly run's four football research records into the canonical artifact."""
import datetime as dt
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "experiments/current-sports-event-research.json"
NOW = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")

def make(slug, event_id, game_id, title, market_id, direction, settlement, official, independents,
         evidence, missing, failures, trigger, next_review, quote_snapshot):
    return {
        "event_slug": slug, "event_id": event_id, "game_id": game_id, "title": title,
        "target_market_id": market_id, "target_side": "YES", "direction": direction,
        "rules_clear": True, "settlement_rules": settlement,
        "research_status": "insufficient", "research_probability": None,
        "confidence_low": None, "confidence_high": None, "calibrated_oos_samples": 0,
        "maximum_acceptable_price": None, "alpha_maximum_acceptable_price": None,
        "method": "Polymarket was used only for contract and executable-price discovery. Public official and independent sources confirm the event and provide qualitative form/team-news context, but the required fresh lineup, opponent-adjusted recent sample, reproducible xG/shot-quality package, weather and reconciled independent P_win were not jointly available. No probability is fabricated.",
        "key_evidence": evidence, "first_goal_profile": "A plausible first-goal route exists from the market and team-strength context, but first-20-minute territory, box entries, set pieces and shot quality were not jointly verified.",
        "trailing_response": "An early opponent goal, 0-0/1-1 low-event path or failure to create repeatable box access breaks a pre-match favourite entry.",
        "lead_protection": "A lead may support controlled possession, but defensive continuity, substitutions and late transition exposure remain unverified.",
        "failure_paths": failures,
        "conditional_trigger": trigger,
        "live_playbook": {"required": "Only study an in-play direction when official score, minute and Polymarket bid/ask are each no older than 120 seconds; monitor the named territorial/chance-quality factor.", "invalidate": "Stale or conflicting state, red card, key injury, major XI change, or two consecutive checkpoints without repeatable attacking evidence."},
        "exit_plan": {"paper": "No paper position. If a later fully evidenced catalyst entry clears the gate, cap at 0.10u, use executable bid for trims and hard-exit before 23:50 Beijing."},
        "research_missing_fields": missing,
        "next_review_at": next_review,
        "strength_classification": "时间段第一/第二候选或强热门；研究证据不足，不是买入授权",
        "sources": [{"kind":"official", **official}] + [{"kind":"independent", **s} for s in independents],
        "source_freshness": {"researched_at": NOW, "quote_snapshot": quote_snapshot},
        "monitoring_level": "M3", "monitoring_activation": "unavailable", "monitoring_owner": "Codex automation; no live owner activated"
    }

def main():
    payload = json.loads(PATH.read_text(encoding="utf-8"))
    by = {str(x.get("event_slug")): x for x in payload.get("research_items", [])}
    common_missing = ["confirmed_starting_XI", "complete_last_5_to_10_opponent_adjusted_results", "verified_xG_or_shot_quality_sequence", "injuries_and_suspensions", "matchday_weather", "independent_P_win_and_confidence_interval", "fresh_CLOB_depth_fees_slippage"]
    rows = [
        make("chi-hen-hai-2026-07-17", "663699", "90108717", "Henan FC vs. Qingdao Hainiu FC", "2787544", "HOME", "Henan FC exact 90-minute win plus stoppage time; extra time and penalties excluded.", {"title":"Chinese Super League official site / resolution source", "url":"https://www.csl-china.com/"}, [{"title":"7M Sport Henan vs Qingdao Hainiu preview", "url":"https://news.7msport.com/news/newsdata/20260716/257923.shtml"},{"title":"SportsGambler Henan vs Qingdao Hainiu preview", "url":"https://www.sportsgambler.com/betting-tips/football/henan-vs-qingdao-hainiu-prediction-lineups-odds-2026-07-17/"},{"title":"FootballAnt Henan vs Qingdao Hainiu lineup and prediction", "url":"https://www.footballant.com/match-news/matches/henan-football-club-vs-qingdao-manatee-lineup-2026/"}], ["CSL source and Polymarket rules identify the exact 90-minute home-win contract.", "Independent previews disagree on the strength of the home route; a projection is not substituted for an independent model.", "Current scan snapshot: 78c ask / 77c bid, 1c spread; fees, depth and slippage must still be rechecked."], common_missing, ["0-0 or 1-1 draw", "Qingdao scores first or wins transition exchanges", "unconfirmed attacking/defensive absences", "red card, penalty or weather/pitch disruption", "fees and slippage consume thin edge"], "WAIT/PASS until confirmed XI, fresh CLOB depth/fees/slippage and a reconciled independent estimate clear the friction-adjusted gate.", "2026-07-17T17:30:00+08:00", "2026-07-17T07:37:45Z"),
        make("chi-bgu-tie-2026-07-17", "663698", "90108716", "Beijing Guoan FC vs. Liaoning Tieren FC", "2787539", "HOME", "Beijing Guoan exact 90-minute win plus stoppage time; extra time and penalties excluded.", {"title":"Chinese Super League official site / resolution source", "url":"https://www.csl-china.com/"}, [{"title":"Sky Sports match page and live status", "url":"https://www.skysports.com/football/beijing-guoan-vs-liaoning-tieren/554304"},{"title":"Theyscored match summary with form, lineups and H2H fields", "url":"https://www.theyscored.com/football/match-summary/beijing-guoan-vs-liaoning-shenyang/3834035"},{"title":"Sofascore match page", "url":"https://www.sofascore.com/football/match/liaoning-tieren-fc-beijing-guoan/BrbsPzNb"}], ["Official CSL resolution source plus independent pages confirm the 17 July 2026 19:35 Beijing fixture.", "Public previews describe a close table/incentive context and do not replace a verified opponent-adjusted model.", "Current scan snapshot: 70c ask / 68c bid, 2c spread; no independent P_win was available."], common_missing, ["draw in a close table matchup", "Liaoning transition or early goal", "unverified rotation/injury", "low-event 0-0/1-1", "stale quote or state"], "WAIT/PASS until confirmed XI, verified recent strength/xG evidence and fresh CLOB depth/fees/slippage are available; no paper entry now.", "2026-07-17T17:30:00+08:00", "2026-07-17T07:37:45Z"),
        make("nor-bog-ffk-2026-07-17", "663524", "90107535", "FK Bodø/Glimt vs. Fredrikstad FK", "2787029", "HOME", "Bodø/Glimt exact 90-minute win plus stoppage time; extra time and penalties excluded.", {"title":"Norwegian FA Eliteserien official fixture listing", "url":"https://www.fotball.no/eliteserien/"}, [{"title":"Fredrikstad official fixture list", "url":"https://www.fredrikstadfk.no/terminliste"},{"title":"Sports Mole Bodo/Glimt vs Fredrikstad preview and team news", "url":"https://www.sportsmole.co.uk/football/bodo-glimt/preview/bodoglimt-vs-fredrikstad-prediction-team-news-lineups_601253.html"},{"title":"VG 2026 team/season context", "url":"https://www.vg.no/sport/i/QJ7vOV/bodoe-glimt-kjoer-over-lang-tid-maa-passe-paa"}], ["Official Norwegian fixture listing confirms 17 July 2026 19:15 local kickoff; current Polymarket snapshot is 86c ask / 85c bid, 1c spread.", "Sports Mole reports absences involving Norway World Cup players and Fredrikstad injuries; this is material but not a full confirmed XI.", "The home price leaves little room for fees, uncertainty and draw mass; market probability is not an independent P_win."], common_missing, ["0-0/1-1 draw", "international-duty absences reduce home quality", "Fredrikstad set-piece or transition goal", "rotation/fatigue after the World Cup break", "high ask plus fees consumes edge"], "WAIT/PASS; recheck confirmed XI and fresh executable CLOB. Do not upgrade the 86c market anchor into research probability.", "2026-07-18T00:30:00+08:00", "2026-07-17T07:37:45Z"),
        make("bra-bah-cha-2026-07-17", "666990", "90104629", "EC Bahia vs. Associação Chapecoense de Futebol", "2798178", "HOME", "Bahia exact 90-minute win plus stoppage time; extra time and penalties excluded.", {"title":"CBF official Série A fixture page", "url":"https://www.cbf.com.br/futebol-brasileiro/jogos/campeonato-brasileiro/serie-a/2026/bahia-x-chapecoense/831927"}, [{"title":"Bahia Notícias probable lineups and match context", "url":"https://www.bahianoticias.com.br/esportes/bahia/33843-bahia-x-chapecoense-confira-provaveis-escalacoes-arbitragem-horario-e-onde-assistir"},{"title":"Sports Mole Bahia vs Chapecoense preview and team news", "url":"https://www.sportsmole.co.uk/football/bahia/preview/bahia-vs-chapecoense-prediction-team-news-lineups_601333.html"},{"title":"Santa Catarina Football Federation preview", "url":"https://fcf.com.br/chapecoense-volta-a-campo-pelo-brasileirao-serie-a-2/"}], ["CBF confirms the rearranged Série A fixture at Arena Fonte Nova on 17 July 2026 19:30 local time.", "Independent reports note a long post-World-Cup break and multiple Chapecoense defensive absences, but list probable rather than confirmed lineups.", "Current scan snapshot: 69c ask / 68c bid, 1c spread; fees, draw mass and unverified XI prevent a research probability."], common_missing, ["low-event draw after long break", "Chapecoense counterattack despite defensive absences", "Bahia rotation or missing creator", "weather/pitch and post-break rhythm", "ask/fee/slippage consumes edge"], "WAIT/PASS until confirmed XI, fresh CLOB depth and an independent reconciled P_win clear the 5c net-edge gate.", "2026-07-18T05:30:00+08:00", "2026-07-17T07:37:45Z")
    ]
    for row in rows: by[row["event_slug"]] = row
    payload.update({"schema_version":"polymarket-sports-event-research-v1", "research_run_id":f"pm-sports-research-{NOW.replace(':','').replace('-','')}", "created_at":NOW, "report_date_beijing":"2026-07-17", "research_items":list(by.values()), "paper_only":True, "live_orders_enabled":False, "private_api_used":False, "real_money_execution_authorized":False})
    PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2)+"\n", encoding="utf-8")
    print(json.dumps({"status":"ok","updated":[r["event_slug"] for r in rows],"research_items":len(by),"created_at":NOW}, ensure_ascii=False))

if __name__ == "__main__": main()
