#!/usr/bin/env python3
"""Push the latest active-alpha paper summary to a WeCom group robot.

Environment:
- ACTIVE_ALPHA_WECOM_WEBHOOK_URL or WECOM_WEBHOOK_URL

The webhook URL is never written to reports or logs. This script sends only
paper-trading status assets generated by wechat_push_assets.py.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
ACTIVE_ROOT = SCRIPT_DIR.parent
WORKSPACE_ROOT = ACTIVE_ROOT.parent
DEFAULT_SUMMARY = ACTIVE_ROOT / "reports" / "LATEST_ACTIVE_ALPHA_PUSH_SUMMARY.md"
DEFAULT_IMAGE = ACTIVE_ROOT / "reports" / "LATEST_ACTIVE_ALPHA_PUSH_CARD.png"
DEFAULT_STATUS = ACTIVE_ROOT / "experiments" / "wecom-push-latest.json"


def rel(path: Path | None) -> str:
    if path is None:
        return "-"
    try:
        return str(path.relative_to(WORKSPACE_ROOT))
    except ValueError:
        return str(path)


def webhook_url() -> str | None:
    return os.environ.get("ACTIVE_ALPHA_WECOM_WEBHOOK_URL") or os.environ.get("WECOM_WEBHOOK_URL")


def post_json(url: str, payload: dict[str, Any], timeout: int) -> dict[str, Any]:
    body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            text = response.read().decode("utf-8", errors="replace")
            try:
                parsed = json.loads(text)
            except json.JSONDecodeError:
                parsed = {"raw": text}
            return {"status": "ok", "http_status": response.status, "response": parsed}
    except urllib.error.HTTPError as exc:
        return {"status": "http_error", "http_status": exc.code, "reason": exc.read().decode("utf-8", errors="replace")}
    except Exception as exc:  # noqa: BLE001
        return {"status": "failed", "reason": f"{type(exc).__name__}: {exc}"}


def markdown_payload(content: str) -> dict[str, Any]:
    # WeCom robot markdown has a practical size limit; keep enough context for phone view.
    clipped = content[:3900]
    return {"msgtype": "markdown", "markdown": {"content": clipped}}


def image_payload(path: Path) -> dict[str, Any]:
    raw = path.read_bytes()
    return {
        "msgtype": "image",
        "image": {
            "base64": base64.b64encode(raw).decode("ascii"),
            "md5": hashlib.md5(raw).hexdigest(),
        },
    }


def write_status(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)
        handle.write("\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Push active-alpha paper dashboard assets to WeCom group robot.")
    parser.add_argument("--summary", default=str(DEFAULT_SUMMARY))
    parser.add_argument("--image", default=str(DEFAULT_IMAGE))
    parser.add_argument("--status-output", default=str(DEFAULT_STATUS))
    parser.add_argument("--timeout", type=int, default=20)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--if-configured", action="store_true", help="Exit ok when webhook env is missing.")
    parser.add_argument("--skip-image", action="store_true")
    parser.add_argument("--compact-output", action="store_true")
    args = parser.parse_args()

    summary_path = Path(args.summary)
    image_path = Path(args.image)
    status_path = Path(args.status_output)
    content = summary_path.read_text(encoding="utf-8") if summary_path.exists() else "Active Alpha Paper Update\nsummary missing"
    url = webhook_url()
    result: dict[str, Any] = {
        "scope": "paper_only_wecom_push",
        "live_orders_enabled": False,
        "private_api_used": False,
        "webhook_configured": bool(url),
        "summary": rel(summary_path),
        "image": rel(image_path) if image_path.exists() else None,
        "dry_run": args.dry_run,
        "sent": [],
        "errors": [],
    }

    if not url:
        result["status"] = "skipped_no_webhook"
        result["operator_note"] = "Set ACTIVE_ALPHA_WECOM_WEBHOOK_URL to enable push. URL is not logged."
        write_status(status_path, result)
        if args.compact_output:
            print(json.dumps(result, ensure_ascii=False))
        return 0 if args.if_configured else 2

    if args.dry_run:
        result["status"] = "dry_run"
        result["operator_note"] = "Webhook configured but no message sent because --dry-run was used."
        write_status(status_path, result)
        if args.compact_output:
            print(json.dumps(result, ensure_ascii=False))
        return 0

    markdown_result = post_json(url, markdown_payload(content), args.timeout)
    result["sent"].append({"type": "markdown", **markdown_result})
    if markdown_result.get("status") != "ok":
        result["errors"].append({"type": "markdown", **markdown_result})

    if not args.skip_image and image_path.exists():
        image_result = post_json(url, image_payload(image_path), args.timeout)
        result["sent"].append({"type": "image", **image_result})
        if image_result.get("status") != "ok":
            result["errors"].append({"type": "image", **image_result})
    elif not args.skip_image:
        result["errors"].append({"type": "image", "status": "missing", "path": rel(image_path)})

    result["status"] = "ok" if not result["errors"] else "partial_or_failed"
    write_status(status_path, result)
    if args.compact_output:
        print(json.dumps(result, ensure_ascii=False))
    else:
        print(result["status"])
    return 0 if result["status"] == "ok" else 1


if __name__ == "__main__":
    raise SystemExit(main())
